### ISSUE TITLE
Possibility to select rows like in the original shiny table

### ISSUE THREAD

**Issue by ma-ef** [astrowonk/shiny_tables#3]
Would it be possible to enhance the functionality by allowing the user to select rows and providing this input to the backend such as with the original shiny datagrid?

**Comment by astrowonk** [comment]
I think a table plugin that worked like that would be great, but it's beyond the scope of this project. The goal is more of the nice looking, but non-interactive tables like `dash-bootstrap-components`. This package is really designed for when table elements, or whatever is inside of the `<td>` needs to be more than numbers (links, buttons, etc.).
